2025-03-29 10:33:20,855 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2025-03-29 10:33:21,191 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-29 10:39:42,538 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2025-03-29 10:39:43,590 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-29 10:40:34,808 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-29 10:42:13,703 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2025-03-29 10:42:14,173 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-29 12:26:36,740 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-29 12:27:01,720 [WARNING] django.request: Not Found: /favicon.ico
2025-03-29 12:28:42,068 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2025-03-29 12:28:42,589 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-29 12:29:27,738 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2025-03-29 12:29:28,628 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 04:43:32,488 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 04:43:54,889 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 04:47:54,611 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2025-03-30 04:47:55,558 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 04:47:58,570 [ERROR] django.request: Internal Server Error: /en/admin/shopapp/product/
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_modify.py", line 65, in submit_row
    add = context["add"]
          ~~~~~~~^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/context.py", line 85, in __getitem__
    raise KeyError(key)
KeyError: 'add'
2025-03-30 04:49:09,201 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 04:49:53,940 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 04:51:28,333 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 04:51:30,950 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 04:54:45,881 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 04:54:51,746 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 04:55:02,346 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 05:02:27,963 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 05:02:31,466 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 05:02:55,745 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 05:03:44,763 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 05:25:43,892 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 05:26:02,200 [WARNING] django.request: Not Found: /
2025-03-30 05:26:02,430 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 05:26:58,902 [ERROR] django.request: Internal Server Error: /en/admin/shopapp/product/import-products-csv/
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'csv_files'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/mysite/shopapp/admin.py", line 84, in import_csv
    form.files["csv_files"].file,
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'csv_files'
2025-03-30 05:29:56,956 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2025-03-30 05:29:58,015 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 05:33:41,135 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2025-03-30 05:33:41,736 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 05:39:07,184 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2025-03-30 05:39:07,791 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 05:40:30,958 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2025-03-30 05:40:31,332 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 05:41:33,555 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2025-03-30 05:41:34,082 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 05:44:29,028 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2025-03-30 05:44:30,017 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 05:44:38,647 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2025-03-30 05:44:38,958 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 05:45:01,672 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2025-03-30 05:45:01,991 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 05:47:19,372 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2025-03-30 05:47:19,736 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 06:02:22,755 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2025-03-30 06:02:23,084 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 06:12:10,262 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/common.py changed, reloading.
2025-03-30 06:12:10,616 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 06:12:25,554 [WARNING] django.request: Method Not Allowed: /ru/shop/api/products/upload_csv/
2025-03-30 06:15:46,951 [WARNING] django.request: Method Not Allowed: /ru/shop/api/products/upload_csv/
2025-03-30 06:16:01,445 [WARNING] django.request: Method Not Allowed: /en/shop/api/products/upload_csv/
2025-03-30 06:29:24,922 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 06:29:40,162 [WARNING] django.request: Not Found: /articles
2025-03-30 06:29:41,280 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 06:29:59,465 [ERROR] django.request: Internal Server Error: /blog/articles/
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: blogapp_article.body

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 160, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: blogapp_article.body
2025-03-30 06:41:29,101 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 06:41:32,441 [ERROR] django.request: Internal Server Error: /blog/articles/
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: blogapp_article.body

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    if match:
       ^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 414, in __bool__
    self._fetch_all()
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 160, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: blogapp_article.body
2025-03-30 06:47:29,436 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 06:47:45,499 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 06:47:56,258 [ERROR] django.request: Internal Server Error: /blog/articles/
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: blogapp_article.body

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    if match:
       ^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 414, in __bool__
    self._fetch_all()
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 160, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: blogapp_article.body
2025-03-30 06:56:09,875 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:06:55,035 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:07:04,691 [WARNING] django.request: Not Found: /
2025-03-30 11:07:07,548 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 11:09:07,878 [WARNING] django.request: Not Found: /en/blog/articles
2025-03-30 11:09:13,773 [WARNING] django.request: Not Found: /en/blog/articles/
2025-03-30 11:09:30,644 [ERROR] django.request: Internal Server Error: /blog/articles/2/
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: blogapp/article_detail.html
2025-03-30 11:12:33,794 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:12:48,347 [ERROR] django.request: Internal Server Error: /blog/articles/2/
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 706, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' %' from 'article.body %'
2025-03-30 11:18:22,329 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2025-03-30 11:18:22,902 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:18:28,293 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2025-03-30 11:18:28,606 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:22:05,121 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2025-03-30 11:22:05,561 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:23:24,750 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/blogapp/urls.py changed, reloading.
2025-03-30 11:23:25,073 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:23:38,818 [ERROR] django.request: Internal Server Error: /blog/articles/latest/feed
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'bloogapp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/syndication/views.py", line 40, in __call__
    feedgen = self.get_feed(obj, request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/syndication/views.py", line 194, in get_feed
    self._get_dynamic_attr("item_link", item),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/syndication/views.py", line 103, in _get_dynamic_attr
    return attr(obj)
           ^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/mysite/blogapp/views.py", line 37, in item_link
    return reverse("bloogapp:article", kwargs={"pk": item.pk})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'bloogapp' is not a registered namespace
2025-03-30 11:24:02,979 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2025-03-30 11:24:03,475 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:34:11,824 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2025-03-30 11:34:12,360 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:35:49,911 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/mysite/urls.py changed, reloading.
2025-03-30 11:35:50,285 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:36:04,211 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:36:17,698 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/mysite/blogapp/sitemap.py", line 10, in items
    return Article.objects.filter(published_at__isnulд=False).order_by("-published_at")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1379, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1423, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'isnulд' for DateTimeField or join on the field not permitted, perhaps you meant isnull?
2025-03-30 11:38:36,733 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2025-03-30 11:38:37,151 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:38:37,866 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/mysite/blogapp/sitemap.py", line 10, in items
    return Article.objects.filter(published_at__isnul=False).order_by("-published_at")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1379, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1423, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'isnul' for DateTimeField or join on the field not permitted, perhaps you meant isnull?
2025-03-30 11:38:41,458 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/mysite/blogapp/sitemap.py", line 10, in items
    return Article.objects.filter(published_at__isnul=False).order_by("-published_at")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1379, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1423, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'isnul' for DateTimeField or join on the field not permitted, perhaps you meant isnull?
2025-03-30 11:38:50,610 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/mysite/blogapp/sitemap.py", line 10, in items
    return Article.objects.filter(published_at__isnull=False).order_by("-published_at")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1379, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1423, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'isnul' for DateTimeField or join on the field not permitted, perhaps you meant isnull?
2025-03-30 11:38:50,678 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/blogapp/sitemap.py changed, reloading.
2025-03-30 11:38:51,182 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:38:52,968 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 121, in sitemap
    lastmod = _get_latest_lastmod(lastmod, site_lastmod)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 36, in _get_latest_lastmod
    new_lastmod = datetime.datetime.combine(new_lastmod, datetime.time.min)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: combine() argument 1 must be datetime.date, not int
2025-03-30 11:39:14,094 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:39:19,579 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 121, in sitemap
    lastmod = _get_latest_lastmod(lastmod, site_lastmod)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 36, in _get_latest_lastmod
    new_lastmod = datetime.datetime.combine(new_lastmod, datetime.time.min)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: combine() argument 1 must be datetime.date, not int
2025-03-30 11:41:18,855 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2025-03-30 11:41:19,161 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:41:25,070 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 121, in sitemap
    lastmod = _get_latest_lastmod(lastmod, site_lastmod)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 36, in _get_latest_lastmod
    new_lastmod = datetime.datetime.combine(new_lastmod, datetime.time.min)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: combine() argument 1 must be datetime.date, not int
2025-03-30 11:48:27,451 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/mysite/sitemaps.py changed, reloading.
2025-03-30 11:48:27,773 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:48:44,114 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/mysite/sitemaps.py changed, reloading.
2025-03-30 11:48:44,484 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:48:50,102 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 121, in sitemap
    lastmod = _get_latest_lastmod(lastmod, site_lastmod)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 36, in _get_latest_lastmod
    new_lastmod = datetime.datetime.combine(new_lastmod, datetime.time.min)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: combine() argument 1 must be datetime.date, not int
2025-03-30 11:51:34,520 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/blogapp/sitemap.py changed, reloading.
2025-03-30 11:51:35,464 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 11:51:38,200 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 121, in sitemap
    lastmod = _get_latest_lastmod(lastmod, site_lastmod)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 36, in _get_latest_lastmod
    new_lastmod = datetime.datetime.combine(new_lastmod, datetime.time.min)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: combine() argument 1 must be datetime.date, not int
2025-03-30 11:52:06,277 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/blogapp/sitemap.py changed, reloading.
2025-03-30 11:52:06,871 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 12:17:47,655 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-30 12:18:08,274 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 124, in _urls
    loc = f"{protocol}://{domain}{self._location(item)}"
                                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 69, in _location
    return self._get("location", item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 39, in _get
    return attr(item)
           ^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 79, in location
    return item.get_absolute_url()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/mysite/shopapp/models.py", line 38, in get_absolute_url
    return reverse("shopapp:product", kwargs={"pk": self.pk})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asha/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'product' not found. 'product' is not a valid view function or pattern name.
2025-03-30 12:18:09,955 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 12:19:23,255 [WARNING] django.request: Not Found: /products/latest/feed/
2025-03-30 12:19:24,451 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 12:19:54,970 [WARNING] django.request: Not Found: /blog/products/latest/feed/
2025-03-30 12:21:42,675 [WARNING] django.request: Not Found: /import-orders/
2025-03-30 12:21:42,881 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 12:23:56,046 [WARNING] django.request: Not Found: /favicon.ico
2025-03-30 12:24:26,096 [WARNING] django.request: Not Found: /products
2025-03-31 01:39:18,006 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-31 01:39:38,747 [INFO] shopapp.views: Rendering shop index
2025-03-31 01:39:39,089 [WARNING] django.request: Not Found: /favicon.ico
2025-03-31 01:51:30,388 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-31 01:51:51,707 [WARNING] django.request: Not Found: /myauth/cookie/get/
2025-03-31 01:51:51,958 [WARNING] django.request: Not Found: /favicon.ico
2025-03-31 01:55:06,688 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/myauth/views.py changed, reloading.
2025-03-31 01:55:07,199 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-31 01:57:18,060 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/urls.py changed, reloading.
2025-03-31 01:57:18,386 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-31 01:57:33,335 [INFO] shopapp.views: Rendering shop index
2025-03-31 02:02:21,425 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2025-03-31 02:02:22,296 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-31 02:02:25,681 [INFO] shopapp.views: Rendering shop index
2025-03-31 02:04:23,946 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2025-03-31 02:04:24,605 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-31 02:08:54,966 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2025-03-31 02:08:55,641 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-31 02:09:11,527 [INFO] shopapp.views: Rendering shop index
2025-03-31 02:09:12,482 [INFO] shopapp.views: Rendering shop index
2025-03-31 02:09:13,503 [INFO] shopapp.views: Rendering shop index
2025-03-31 02:15:13,729 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-31 02:23:24,271 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2025-03-31 02:23:25,024 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-03-31 02:27:03,190 [INFO] django.utils.autoreload: /home/asha/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2025-03-31 02:27:04,543 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
